### PR TITLE
Redesign program

### PR DESCRIPTION
**Pull request by itsisak**
Redisign program to fit more details about each event. This aims to replace the "info" pages. 

https://github.com/itdagene-ntnu/itdagene-webapp/assets/45620425/cf04a7cc-b49f-4bb7-b569-d48ca6d91a93

This has a lot of more potential, both the result and the code can be better, but this is to get a start at least and to be more <i>AGILE</i> 🏎️ in our development.

### CODE REVIEW

**Review by falbru — COMMENTED** [review]
Looks so much better 🤯

**Review by falbru — APPROVED** [review]

**Comment by itsisak** [comment]
Tests work locally (`yarn test`), but these tests will fail until backend PR is merged.

**Review by falbru — APPROVED** [review]
This looks AMAZING! Very good job.

**Review by aleksandervestlund — APPROVED** [review]
Looks sooooo much better😍😍

**Pull request merged**
