### PR TITLE
Program-UI

### PR DESCRIPTION
**Pull request by olestole**
Update the program-UI and add frontend support for markdown.

itDAGENE_programUI

### CODE REVIEW

**Comment by olestole** [comment]
Agreed, what are your thoughts on this? @LudvigHz 

image

**Comment by LudvigHz** [comment]
> Agreed, what are your thoughts on this? @LudvigHz
> 
> image

Yeah, I think that's better :+1:

**Comment by LudvigHz** [comment]
Status on this @olestole ? Is it just missing the fixes discussed, or is it ready for merge?

**Comment by olestole** [comment]
> Status on this @olestole ? Is it just missing the fixes discussed, or is it ready for merge?

Oops, I've forgotten to push the latest fix. I'll be right on it

**Pull request merged**
